
# org: gaurangkhator
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cashtrail-expense-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource: "*"

  httpApi:
    cors:
      allowedOrigins: 
        - http://localhost:3000
        - https://cashtrail-app.vercel.app
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - GET
        - POST 
        - OPTIONS
        - PUT 
        - DELETE

functions:
  createExpense:
    handler: handlers/createExpense.createExpense
    events:
      - httpApi:
          path: /expenses
          method: post

  getExpense:
    handler: handlers/getExpense.getExpense
    events:
      - httpApi:
          path: /expenses
          method: get

  deleteExpense:
    handler: handlers/deleteExpense.deleteExpense
    events:
      - httpApi:
          path: /expenses/{expenseId}
          method: delete

  updateExpense:
    handler: handlers/updateExpense.updateExpense
    events:
      - httpApi:
          path: /expenses/{expenseId}
          method: put

  createIncome:
    handler: handlers/createIncome.createIncome
    events: 
      - httpApi:
          path: /income 
          method: post

  getIncome:
    handler: handlers/getIncome.getIncome
    events: 
      - httpApi:
          path: /income 
          method: get 

  deleteIncome:
    handler: handlers/deleteIncome.deleteIncome
    events: 
      - httpApi: 
          path: /income/{incomeId}
          method: delete 

  updateIncome:
    handler: handlers/updateIncome.updateIncome
    events:
      - httpApi:
          path: /income/{incomeId}
          method: put

resources:
  Resources:
    ExpensesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Expenses
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: expenseId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: expenseId
            KeyType: RANGE

    MonthlyIncomeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Income 
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: incomeId 
            AttributeType: S 
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: incomeId
            KeyType: RANGE